### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by DavideBordoni** [spacys/mediathek#54] opened 2020-10-15 10:56 UTC
It seems that amazon music login was changed.
Currently parsing login page fails due to missing match on login.

It happens to me on https://music.amazon.it
Thanks,
Davide

**Comment by spacys** [comment] 2020-10-25 09:29
Could you please go to the addon settings, click on "Reset Addon", afterwards set your damain to "IT" and try to login.

**Comment by DavideBordoni** [comment] 2020-11-08 07:35
I did try to reset, the plugin. Remove and install it again from your repository (Spacy's Repository) and add some log line but, it seems that login page (i did add a log in the code to view the login page) given is not managed by the plugin.
Thanks

**Comment by spacys** [comment] 2020-11-09 20:05
You are right, Amazon changed the Logon page again. The new version in feature branch can manage the new page. I'll check and transfer this to the master branch in the next couple of days.

**Comment by pipip** [comment] 2020-11-22 12:06
@spacys Did you already update the addon? Login still fails for me (v0.2.0)

**Comment by spacys** [comment] 2020-11-22 13:09
A fix is in the future branch available, I'll transfer this to the master branch in the next days.

**Comment by spacys** [comment] 2020-12-13 17:34
Is this issue still present or was it fixed with the last version update?

**Comment by pipip** [comment] 2020-12-13 19:00
no, still can't login with 0.2.1 :(

**Comment by FWinkler79** [comment] 2021-01-03 11:39
Is this fixed now? I tried installing the zip of version 0.2.0 and could also not login.
If it were fixed in the master, could you also please provide a new zip file for download?
Thanks!

**Comment by spacys** [comment] 2021-01-03 12:01
Yes, the logon issue is fixed with version 0.2.1
https://github.com/spacys/mediathek/blob/master/plugin.audio.amazonmedia/plugin.audio.amazonmedia-0.2.1.zip
Please try again. If it is still not working then I need some more details, but take care about your personal data.

**Comment by FWinkler79** [comment] 2021-01-16 20:12
Thanks. I tried, and even though I can login, I cannot play back any of the songs.

```
2021-01-16 21:01:03.158 T:2973297760   ERROR: Control 55 in window 10502 has been asked to focus, but it can't
2021-01-16 21:02:22.386 T:2973297760  NOTICE: VideoPlayer::OpenFile: plugin://plugin.audio.amazonmedia/?asin=<some asin>&mode=getTrack&objectId=49d70434-9c47-4564-b447-79c058ce9ef7
2021-01-16 21:02:22.392 T:2268283088  NOTICE: Creating InputStream
2021-01-16 21:02:23.355 T:2268283088   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
2021-01-16 21:02:23.355 T:2268283088   ERROR: CCurlFile::Open failed with code 400 for https://music.amazon.de/EU/api/dmls/:
2021-01-16 21:02:23.355 T:2268283088   ERROR: AddOnLog: InputStream Adaptive: License server returned failure
2021-01-16 21:02:23.355 T:2268283088   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
2021-01-16 21:02:23.384 T:2268283088   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
2021-01-16 21:02:23.385 T:2268283088   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.audio.amazonmedia/?asin=<some asin>&mode=getTrack&objectId=49d70434-9c47-4564-b447-79c058ce9ef7]
2021-01-16 21:02:23.385 T:2268283088  NOTICE: CVideoPlayer::OnExit()
2021-01-16 21:02:23.411 T:2973297760  NOTICE: CVideoPlayer::CloseFile()
2021-01-16 21:02:23.412 T:2973297760  NOTICE: VideoPlayer: waiting for threads to exit
2021-01-16 21:02:23.412 T:2973297760  NOTICE: VideoPlayer: finished waiting
2021-01-16 21:02:38.953 T:2973297760  NOTICE: VideoPlayer::OpenFile: plugin://plugin.audio.amazonmedia/?asin=<some asin>&mode=getTrack&objectId=49d70434-9c47-4564-b447-79c058ce9ef7
2021-01-16 21:02:38.955 T:2285068496  NOTICE: Creating InputStream
2021-01-16 21:02:39.750 T:2285068496   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
2021-01-16 21:02:39.750 T:2285068496   ERROR: CCurlFile::Open failed with code 400 for https://music.amazon.de/EU/api/dmls/:
2021-01-16 21:02:39.750 T:2285068496   ERROR: AddOnLog: InputStream Adaptive: License server returned failure
2021-01-16 21:02:39.750 T:2285068496   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
2021-01-16 21:02:39.778 T:2285068496   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
2021-01-16 21:02:39.780 T:2285068496   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.audio.amazonmedia/?asin=<some asin>&mode=getTrack&objectId=49d70434-9c47-4564-b447-79c058ce9ef7]
2021-01-16 21:02:39.780 T:2285068496  NOTICE: CVideoPlayer::OnExit()
2021-01-16 21:02:39.795 T:2973297760  NOTICE: CVideoPlayer::CloseFile()
2021-01-16 21:02:39.795 T:2973297760  NOTICE: VideoPlayer: waiting for threads to exit
2021-01-16 21:02:39.795 T:2973297760  NOTICE: VideoPlayer: finished waiting
```

Is this me, or is that a general problem?

**Comment by spacys** [comment] 2021-01-18 18:32
This depends on the operating system, please check the [known issues](https://github.com/spacys/mediathek/blob/master/README.md).
Libreelec is working again and I have to update the readme file. I assume you are on one of the mentioned systems. Right?!?
Did you modified the log and removed the asin information to see this in the log: "asin=<some asin>" No issue, just for my understanding. "asin" is the interpreterID/albumID/playlistID/songID depending on the context.

**Comment by FWinkler79** [comment] 2021-01-18 19:04
I am on Raspbian directly.
And yes, I modified the log above to include `sin=<some asin>` instead of the real asin.
I did not know what it was for and did not want to risk exposing anything sensitive.

FYI, I also have the `InputStream Helper` installed on Kodi, which keeps the Widevine lib up to date.
So it shouldn't be due to an outdated Widevine version.

**Comment by spacys** [comment] 2021-01-24 09:24
Does this occur for every song/album, also for the own songs and stations as well?
I do not have the possibility to check the Raspbian functionality. But usually it is related to the OS libraries.
Maybe you can check the logs for other issues.

**Comment by nrpetonr** [comment] 2021-01-24 13:05
@ spacys, similar for me, can not login. actually does it ask for initial login after opening (i do not see option in the setting for credentials)? 

 ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'LOGNOTICE'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 46, in <module>
                                                       class AmazonMedia():
                                                     File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 302, in AmazonMedia
                                                       def log(self, msg, level=xbmc.LOGNOTICE):
                                                   AttributeError: module 'xbmc' has no attribute 'LOGNOTICE'
                                                   -->End of Python script error report<--

**Comment by spacys** [comment] 2021-01-24 13:55
@nrpetonr, looks your Kodi is not fully installed. Which version of Kodi and OS is in use?
`xbmc.LOGNOTICE` is a default xbmc/kodi function.

**Comment by nrpetonr** [comment] 2021-01-24 14:02
it's matrix RC1 on coreelec. works fine. let me test on leia...

**Comment by nrpetonr** [comment] 2021-01-24 14:30
it's different  on leia, it's at least trying to log in, but fails at the end. log is different   https://pastebin.com/nme8nHwN

**Comment by spacys** [comment] 2021-01-25 18:21
Have you tried to reset the addon?

**Comment by nrpetonr** [comment] 2021-01-25 18:50
yup, couple of times. can it be, than my country is CZ and your addon does not offer it?

**Comment by spacys** [comment] 2021-01-28 21:45
Good point, that could be the reason. Maybe you can provide the translation, then I can add the country code CZ in the settings.
Just for testing purpose, you can search in the settings file for `<setting id="siteVersion"       type="enum" label="30101" values="DE|FR|UK|IT|ES" default="0"/>`. Add '|CZ' as additional value and change the default to '5'. That should work as a workaround.

**Comment by nrpetonr** [comment] 2021-01-30 12:05
tested with CZ, unfortunately still not working. it does not even load login screens with user and pass. i am reading the log, but not really finding the root cause, bug i am just beginner.

> 2021-01-30 12:55:19.670 T:3203322752   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: loading setting definitions
2021-01-30 12:55:19.670 T:3203322752   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: trying to load setting definitions from old format...
2021-01-30 12:55:19.672 T:3203322752   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: loading setting values
2021-01-30 12:55:19.677 T:3203322752   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 2575, in <module>
                                                amz = AmazonMedia()
                                              File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 62, in __init__
                                                self.setVariables()
                                              File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 86, in setVariables
                                                self.logonURL     = 'https://www.amazon.{}/gp/aw/si.html'.format(self.siteVerList[int(self.siteVersion)])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2021-01-30 12:55:19.677 T:3203322752   DEBUG: onExecutionDone(30, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py)
2021-01-30 12:55:19.677 T:3262071680   DEBUG: CVideoPlayerVideo::OutputPicture - ttd:-177ms pts:1640.364 Clock:1640.542 Level:0
2021-01-30 12:55:19.680 T:4065280016   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-01-30 12:55:19.706 T:3203322752    INFO: Python interpreter stopped
2021-01-30 12:55:19.706 T:3203322752   DEBUG: Thread LanguageInvoker 3203322752 terminating
2021-01-30 12:55:19.708 T:3194930048   ERROR: GetDirectory - Error getting plugin://plugin.audio.amazonmedia/
2021-01-30 12:55:19.708 T:3194930048   DEBUG: Thread waiting 3194930048 terminating
2021-01-30 12:55:19.709 T:3262071680   DEBUG: CVideoPlayerVideo::OutputPicture - ttd:-196ms pts:1640.384 Clock:1640.581 Level:1
2021-01-30 12:55:19.710 T:3262071680   DEBUG: CVideoPlayerVideo::OutputPicture - ttd:-177ms pts:1640.404 Clock:1640.582 Level:2
2021-01-30 12:55:19.711 T:3262071680   DEBUG: CVideoPlayerVideo::OutputPicture - ttd:-159ms pts:1640.424 Clock:1640.583 Level:3
2021-01-30 12:55:19.712 T:3262071680   DEBUG: CVideoPlayerVideo::OutputPicture - ttd:-140ms pts:1640.444 Clock:1640.585 Level:4
2021-01-30 12:55:19.714 T:3262071680   DEBUG: CVideoPlayerVideo::OutputPicture - ttd:-121ms pts:1640.464 Clock:1640.586 Level:5
2021-01-30 12:55:19.715 T:3262071680   DEBUG: CVideoPlayerVideo::OutputPicture - ttd:-102ms pts:1640.484 Clock:1640.587 Level:6
2021-01-30 12:55:19.716 T:3262071680   DEBUG: CVideoPlayerVideo::OutputPicture - ttd:-84ms pts:1640.504 Clock:1640.589 Level:0
2021-01-30 12:55:19.718 T:3262071680   DEBUG: CVideoPlayerVideo::OutputPicture - ttd:-65ms pts:1640.524 Clock:1640.590 Level:1
2021-01-30 12:55:19.723 T:4065280016   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2021-01-30 12:55:19.724 T:4065280016   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.amazonmedia/) failed
2021-01-30 12:55:19.735 T:4065280016   DEBUG: CGUIMediaWindow::GetDirectory ()
2021-01-30 12:55:19.735 T:4065280016   DEBUG:   ParentPath = [plugin://plugin.audio.amazonmedia/]
2021-01-30 12:55:19.746 T:3194930048   DEBUG: Thread waiting start, auto delete: false

>

**Comment by nrpetonr** [comment] 2021-01-30 12:23
if a switch back to any of standard countries, it loads the login screens with user and pass, starts connecting, but fails with message "login was not possible".

> DEBUG: ------ Window Init (DialogAddonInfo.xml) ------
2021-01-30 13:13:58.983 T:4065280016   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: loading setting definitions
2021-01-30 13:13:58.983 T:4065280016   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: trying to load setting definitions from old format...
2021-01-30 13:13:58.985 T:4065280016   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: loading setting values

2021-01-30 13:14:12.220 T:3220108160   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 2575, in <module>
                                                amz = AmazonMedia()
                                              File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 62, in __init__
                                                self.setVariables()
                                              File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 86, in setVariables
                                                self.logonURL     = 'https://www.amazon.{}/gp/aw/si.html'.format(self.siteVerList[int(self.siteVersion)])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2021-01-30 13:14:12.220 T:3220108160   DEBUG: onExecutionDone(57, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py)
2021-01-30 13:14:12.222 T:4065280016   DEBUG: ----a-- Window Init (DialogNotification.xml) ------
2021-01-30 13:14:12.226 T:3262071680   DEBUG: CVideoPlayerVideo::OutputPicture - ttd:115ms pts:2773.124 Clock:2773.009 Level:6
2021-01-30 13:14:12.237 T:3220108160    INFO: Python interpreter stopped
2021-01-30 13:14:12.237 T:3220108160   DEBUG: Thread LanguageInvoker 3220108160 terminating
2021-01-30 13:14:12.241 T:3236893568   ERROR: GetDirectory - Error getting plugin://plugin.audio.amazonmedia/
2021-01-30 13:14:12.241 T:3236893568   DEBUG: Thread waiting 3236893568 terminating

>

**Comment by spacys** [comment] 2021-01-31 13:11
Oh, yes, there is an additional change necessary. In the file `amazonmedia.py`, in the function `def setVariables(self):` replace `self.siteVerList  = ["de", "fr", "co.uk", "it", "es"]` with `self.siteVerList  = ["de", "fr", "co.uk", "it", "es", "cz"]`.
With this change the error message `IndexError: list index out of range` should not appear anymore.

**Comment by nrpetonr** [comment] 2021-01-31 15:12
step forward, but still failing. don't bother spacys, thanks anyway. will just use phone over bluetooth

	Line 154: 2021-01-31 16:05:47.906 T:4060639248  NOTICE: ADDON: plugin.audio.amazonmedia v0.2.2 installed
	Line 158: 2021-01-31 16:05:47.906 T:4060639248  NOTICE: ADDON: plugin.video.amazon-test v0.9.0 installed
	Line 187: 2021-01-31 16:05:47.906 T:4060639248  NOTICE: ADDON: script.module.amazon.database v0.1.1 installed
	Line 567: 2021-01-31 16:05:49.184 T:4060639248   DEBUG: POParser: PO file has Win Style Line Endings. Converted in memory to Linux LF for file: /storage/.kodi/addons/plugin.video.amazon-test/resources/language/resource.language.en_gb/strings.po
	Line 578: 2021-01-31 16:05:49.214 T:4060639248   DEBUG: LocalizeStrings: loaded 56 strings from file /storage/.kodi/addons/plugin.audio.amazonmedia/resources/language/resource.language.en_gb/strings.po
	Line 3590: 2021-01-31 16:06:18.429 T:4060639248   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: loading setting definitions
	Line 3591: 2021-01-31 16:06:18.429 T:4060639248   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: trying to load setting definitions from old format...
	Line 3592: 2021-01-31 16:06:18.431 T:4060639248   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: loading setting values
	Line 3840: 2021-01-31 16:06:42.079 T:4060639248   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.audio.amazonmedia/)
	Line 3841: 2021-01-31 16:06:42.079 T:4060639248   DEBUG:   ParentPath = [plugin://plugin.audio.amazonmedia/]
	Line 3843: 2021-01-31 16:06:42.097 T:3914302336   DEBUG: CAddonDatabase::SetLastUsed[plugin.audio.amazonmedia] took 18 ms
	Line 3844: 2021-01-31 16:06:42.097 T:3903460224   DEBUG: StartScript - calling plugin Amazon Media('plugin://plugin.audio.amazonmedia/','3','','resume:false')
	Line 3844: 2021-01-31 16:06:42.097 T:3903460224   DEBUG: StartScript - calling plugin Amazon Media('plugin://plugin.audio.amazonmedia/','3','','resume:false')
	Line 3847: 2021-01-31 16:06:42.098 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): start processing
	Line 3847: 2021-01-31 16:06:42.098 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): start processing
	Line 3849: 2021-01-31 16:06:42.124 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): the source file to load is "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py"
	Line 3849: 2021-01-31 16:06:42.124 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): the source file to load is "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py"
	Line 3849: 2021-01-31 16:06:42.124 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): the source file to load is "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py"
	Line 3849: 2021-01-31 16:06:42.124 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): the source file to load is "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py"
	Line 3850: 2021-01-31 16:06:42.125 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): setting the Python path to /storage/.kodi/addons/plugin.audio.amazonmedia:/storage/.kodi/addons/script.module.beautifulsoup4/lib:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.mechanize/lib:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
	Line 3850: 2021-01-31 16:06:42.125 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): setting the Python path to /storage/.kodi/addons/plugin.audio.amazonmedia:/storage/.kodi/addons/script.module.beautifulsoup4/lib:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.mechanize/lib:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
	Line 3850: 2021-01-31 16:06:42.125 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): setting the Python path to /storage/.kodi/addons/plugin.audio.amazonmedia:/storage/.kodi/addons/script.module.beautifulsoup4/lib:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.mechanize/lib:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
	Line 3851: 2021-01-31 16:06:42.125 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): entering source directory /storage/.kodi/addons/plugin.audio.amazonmedia
	Line 3851: 2021-01-31 16:06:42.125 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): entering source directory /storage/.kodi/addons/plugin.audio.amazonmedia
	Line 3851: 2021-01-31 16:06:42.125 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): entering source directory /storage/.kodi/addons/plugin.audio.amazonmedia
	Line 3852: 2021-01-31 16:06:42.125 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): instantiating addon using automatically obtained id of "plugin.audio.amazonmedia" dependent on version 0.0.0 of the xbmc.python api
	Line 3852: 2021-01-31 16:06:42.125 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): instantiating addon using automatically obtained id of "plugin.audio.amazonmedia" dependent on version 0.0.0 of the xbmc.python api
	Line 3852: 2021-01-31 16:06:42.125 T:3526353792   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): instantiating addon using automatically obtained id of "plugin.audio.amazonmedia" dependent on version 0.0.0 of the xbmc.python api
	Line 3854: 2021-01-31 16:06:42.529 T:3526353792   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: loading setting definitions
	Line 3855: 2021-01-31 16:06:42.529 T:3526353792   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: trying to load setting definitions from old format...
	Line 3856: 2021-01-31 16:06:42.530 T:3526353792   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: loading setting values
	Line 3857: 2021-01-31 16:06:42.538 T:3526353792  NOTICE: [Amazon Media] Handle: 3
	Line 3860: 2021-01-31 16:06:42.540 T:3526353792   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: loading setting definitions
	Line 3861: 2021-01-31 16:06:42.540 T:3526353792   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: trying to load setting definitions from old format...
	Line 3862: 2021-01-31 16:06:42.541 T:3526353792   DEBUG: CAddonSettings[plugin.audio.amazonmedia]: loading setting values
	Line 3868:                                               File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 2576, in <module>
	Line 3868:                                               File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 2576, in <module>
	Line 3870:                                               File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 142, in reqDispatch
	Line 3870:                                               File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 142, in reqDispatch
	Line 3871:                                                 if not self.access and not self.amazonLogon():
	Line 3872:                                               File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 724, in amazonLogon
	Line 3872:                                               File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 724, in amazonLogon
	Line 3872:                                               File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 724, in amazonLogon
	Line 3890: 2021-01-31 16:06:42.679 T:3526353792   DEBUG: onExecutionDone(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py)
	Line 3890: 2021-01-31 16:06:42.679 T:3526353792   DEBUG: onExecutionDone(19, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py)
	Line 3894: 2021-01-31 16:06:42.841 T:3903460224   ERROR: GetDirectory - Error getting plugin://plugin.audio.amazonmedia/
	Line 3897: 2021-01-31 16:06:42.848 T:4060639248   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.amazonmedia/) failed
	Line 3899: 2021-01-31 16:06:42.855 T:4060639248   DEBUG:   ParentPath = [plugin://plugin.audio.amazonmedia/]

**Comment by dfrey** [comment] 2021-02-21 19:09
HI all, 
I am new here. I just tried version 0.2.2. It accepts my email and password but I get the following error in the log. Any ideas? Am I using the right version? 
thanks


2021-02-21 19:58:14.141 T:2353692880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 2576, in <module>
                                                amz.reqDispatch()
                                              File "/home/pi/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 142, in reqDispatch
                                                if not self.access and not self.amazonLogon():
                                              File "/home/pi/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 773, in amazonLogon
                                                app_config = json.loads(script)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
                                                obj, end = self.scan_once(s, idx)
                                              File "/usr/lib/python2.7/json/decoder.py", line 36, in errmsg
                                                lineno, colno = linecol(doc, pos)
                                            TypeError: 'NoneType' object is not callable
                                            -->End of Python script error report<--
2021-02-21 19:58:14.267 T:2362085584   ERROR: GetDirectory - Error getting plugin://plugin.audio.amazonmedia/
2021-02-21 19:58:14.287 T:2973288480   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.amazonmedia/) failed

**Comment by spacys** [comment] 2021-02-22 21:57
Kodi 19 was released, I'm working on an updated version at the moment, planned release is end of this week.

**Comment by dfrey** [comment] 2021-02-22 22:28
Thanks,  
will it work on 18.7 as well? Raspbian only carries 18.7 for now. Also I have other add-ons that do not yet support 19.0
thanks

Davide Frey

**Comment by spacys** [comment] 2021-02-23 20:46
New version for Kodi 19 only is now available.

**Comment by spacys** [comment] 2021-03-09 20:45
Is the logon issue still present or is it resolved now?

**Comment by spacys** [comment] 2021-03-11 23:03
Only Kodi 19 is supported.

**Comment by FWinkler79** [comment] 2021-03-12 09:32
Then unfortunately I cannot provide feedback at this point in time.
Once Kodi 19 is available for Raspbian I will upgrade and give it a try.

**Comment by spacys** [comment] 2021-04-03 15:49
I assume the logon issues are resolved now with Kodi 19 and the latest version of this addon. Therefore I'll close this issue now.

**Closed as completed by spacys** 2021-04-03 15:49 UTC
