### ISSUE TITLE
no audio on Libreelec 9.2.1 /Kodi 18.6

### ISSUE THREAD

**Issue by tommi296** [spacys/mediathek#26] opened 2020-04-03 12:08 UTC
not sure, if this is the right place to report problems.

Anyway: addon is installed, login is working, but I get no audiostream. Error message:
2020-04-03 11:37:30.340 T:1490019200   ERROR: Open - error probing input format, /storage/.kodi/userdata/addon_data/plugin.audio.amazonmedia/song.mpd
2020-04-03 11:37:30.340 T:1490019200   ERROR: OpenDemuxStream - Error creating demuxer

Is this still the DRM issue?

**Comment by spacys** [comment] 2020-04-05 07:35
This is the right place to report any issues with this addon.
The root cause for the playback issues with Libreelec is not identified so far. I assume this has something to do with the distro itself, because on other Linux systems there is no issue.
Do you have the chance to check the addon with an older version of Libreelec and in addition inputstream.adaptive is already activated?

**Comment by tommi296** [comment] 2020-04-05 16:11
no change with Libreelec 9.0.2 and 8.2.5
I got Amazon VOD to work, but still an issue with inputstream.adaptive; error:
"InputStream Adaptive: License server returned failure"; checking with Kodi support...

**Comment by gd71** [comment] 2020-04-21 09:36
Hi,
same issue on my rasberry pi 4 with raspbian
looks like this line
https://github.com/spacys/mediathek/blob/6aed72dc2299b55c4166509be8c1d273dc411976/source/plugin.audio.amazonmedia/amazonmedia.py#L2388
set type to video and is hiding the real problem.
If you set the type to audio, you will fall into the VMP_VALIDATION_FAILED issue which mean that your device is not registered
At least it is the case for me on Raspbian and windows. Works well on linux (don't know why) and Android (because decoding is transmitted to a registered dedicated chipset)

**Comment by spacys** [comment] 2020-04-21 10:31
I assume this is the nature of the VMP validation. Which is not present on Linux and Andoid...well, it is from google (same as widevine library).

Current status:
- addon is working on Linux and Android
- not working on Windows, raspi and Libreelec

**Comment by gd71** [comment] 2020-04-21 10:40
yep, but raspbian and libreelec are linux.
VMP validation is present also on android but managed directly by a chip burned for.
I'm not aware enough to go deeper in the details but we might have a better explanation coming from inpustream.adaptive devs

**Comment by spacys** [comment] 2020-04-23 11:26
Raspi and Libreelec are ARM based.
Honestly I don't know how to solve this issue.

**Comment by gd71** [comment] 2020-04-23 12:09
Oh, sorry, I didn't say that. My apologies for my soo bad English (Usual for French guys btw :) )
Just wanted to try to clarify things.
You're right and until now, nobody on my knowledge have been able to implement the VMP validation on such systems.
AFAIK:
The entire application must be signed and registered within google widevine, obviously kodi will never being registered. (eg : Firefox is)
Previous levels of license request challenge only required the widevine library and are provided by the inpustreamhelper module which extract the library from chromeOS for the platform.
https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf
This link describe the dl location for each supported platform (which include many ARM based platforms).
I'm just asking myself why x86 based linux boxes are not affected but ARM linux boxes are.
I will try to check whether a more appropriate library is available following this link instead of relying on the inputstreamhelper.

**Comment by spacys** [comment] 2020-04-23 12:44
No issue, I checked so many things in the last couple of days/weeks...
It is just a bit frustrating if I see the addon functionality and the user advantages and then it is not working on all platforms due to widevine restrictions.
Cross the fingers...maybe we will find a proper solution in the future.

**Comment by gd71** [comment] 2020-04-23 14:03
https://www.widevine.com/news
```
All Widevine browser-based integrations (platforms and applications) must support VMP. VMP support is NOT available for Linux platforms.

The Widevine License Service API update (allow_unverified_platform) retains current default permissive behavior.
```
Meaning if platform = linux then go permissive
=> need to find a way to always detect as linux platform ?
But I guess this will be fixed soon or late

**Comment by spacys** [comment] 2020-05-01 12:10
Readme was updated and the issue can considered in the future.

**Closed as completed by spacys** 2020-05-01 12:10 UTC

**Comment by michaelarnauts** [comment] 2021-02-06 20:02
Really odd, but we've just noticed exactly the same issue with another service.

Playback works fine on Android and Ubuntu, but it doesn't on RPI's or Windows.
